spring.application.name=Smart-Task-Management-System

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=david
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=task_management_shema
management.endpoints.web.exposure.include=mappings